### ISSUE TITLE
Option to turn off some bindings?

### ISSUE THREAD

**Issue by sid-kap** [jorgenschaefer/typoel#10]
I'd like to add options to selectively turn on characters. For example, I might only want the hyphen shortcut, but none of the others. Does this seem like a good idea/would you consider merging such a feature?

**Comment by jorgenschaefer** [comment]
You can easily change `typo-mode-map` to set keys you don't like to `nil` – is that not enough?

**Comment by sid-kap** [comment]
Could you provide an example of how to do that? Sorry, I'm new to Emacs/Elisp

**Comment by jorgenschaefer** [comment]
This should disable the special binding for `<`, for example:

```Lisp
(load "typo")
(define-key typo-mode-map (kbd "<") nil)
```

Does this help?

**Comment by sid-kap** [comment]
Yes, that does what I want. Thanks!

**Comment by jorgenschaefer** [comment]
Glad it works, enjoy this little extension :-)
