### ISSUE TITLE
easy entering '--' instead of '–'

### ISSUE THREAD

**Issue by gour** [jorgenschaefer/typoel#11]
Hello,

I'm very happy with typoel package which allows easy entry of typographical stuff in my text...

Now, have a problem for which I do not find easy solution: I'm using Hugo static-site generator along with Asciidoc(tor) markup and in order to mark summary separator for blog post one has to enter the following:

```
<!--more-->
```
which consists of few 'special' combinations like '--' and '->' recognized by typoel which are converted into their typographical equivalents, so the question is what would be recommended way to enter the above code easily?

So far, I've created "C-x t" binding in order to able to quickly switch on/off typo-mode. Anything else?

**Comment by jorgenschaefer** [comment]
Hello! You can use `C-q` to avoid special handling of the following key, so e.g. `- C-q -` should work. Does that help? :-)

**Comment by gour** [comment]
> Does that help? :-)

Perfect. ;)
