### ISSUE TITLE
Arrow not inserted

### ISSUE THREAD

**Issue by nico202** [jorgenschaefer/typoel#12]
Hi, looking at the code I see that with -> it should insert an arrow, but for me it's not working (while ...) is.
Can you confirm it is working? Thanks

**Comment by jorgenschaefer** [comment]
After `M-x typo-global-mode`, `C-c 8 - >` should work. Does it?

**Comment by nico202** [comment]
Yes, C-c  8 does the trick. It's possible to do it automatically?

**Comment by jorgenschaefer** [comment]
You can do `(global-set-key (kbd "->") "→")`, but that's probably not what you want :-) What you're looking for is not there by default in typo.el.

**Comment by nico202** [comment]
Ok, thanks!
