### ISSUE TITLE
Support U+02BC for apostrophes

### ISSUE THREAD

**Issue by aaronjensen** [jorgenschaefer/typoel#15]
Hi, thank you for this package, it's great.

The current handling of apostrophes (replacing them with right quotes) led me down a path of trying to get right quotes to behave like apostrophes in emacs:

https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30815

My conclusion from that is based on this article:

https://tedclancy.wordpress.com/2015/06/03/which-unicode-character-should-represent-the-english-apostrophe-and-why-the-unicode-committee-is-very-wrong/

If I'm going to use something other than `'` for an apostrophe, I'd rather use `U+02BC` as it works out of the box in emacs and doesn't have the problems described in the article above.

What would you think about adding support for that to typo?

Thanks!

**Comment by jorgenschaefer** [comment]
Hello, and thanks for the comment! You should easily be able to configure typo.el to use whatever code point you like for the apostrophe by adjusting `typo-cycle-right-single-quotation-mark`. I would rather not use some niche opinion about what is or is not "correct" to typo.el – the package can stick to the official position, if someone disagrees, they can easily customize things :-)

**Comment by aaronjensen** [comment]
Thanks, I understand. One thing that would be nice would be the ability to differentiate between quotes and apostrophes--if there's no opening single quote, insert an "apostrophe" which could be configured as the user wants (and default to right quote). AFAICT, configuring it as you suggest would lead to single quoted things being closed with apostrophes by default rather than right quotes. Maybe I'm misunderstanding though.

**Comment by jorgenschaefer** [comment]
I'm not sure what you are proposing – you can easily bind the apostrophe key to your own command, if that requires more logic than traditional typesetting?
