### ISSUE TITLE
Don't replace ligatures

### ISSUE THREAD

**Issue by tmalsburg** [jorgenschaefer/typoel#4]
In the README, you say that you may add support for ligatures in the future.  I agree, that ligatures should rather be a display issue.  A concrete problem with replacing ligatures is that a search for things like `fi` would fail. For instance, when I search for occurrences of *artificial* in a document that wouldn't turn up anything because the `fi` sequence has been replaced by the corresponding ligature.  Another problem is that most people use mono-spaced fonts in Emacs and ligatures arguably don't make sense in mono-space fonts.

**Comment by jorgenschaefer** [comment]
I agree with your conclusion, but not your reasons :-)

Unicode defines decomposition rules which make it easy to allow searching for for "fi" to find "ﬁ". Browsers do this, you can test it with the glyphs there, but Emacs does not. That's a bug in Emacs, not the glyph. A similar problem exists right now with searching for quotation marks or the single apostrophe, though (or even the ellipsis and periods).

The monospace argument holds true for e.g. the ellipsis, too, as a single-glyph ellipsis only makes sense in variable-width fonts, but as documents are regularly exported from Emacs to variable-width displays (e.g. HTML), these glyphs still make sense. So would ligatures.

More convincing to me is that it's difficult to know when to actually create a ligature. This can be quite involved, as for example "self" should get a ligature but "welfare" should not. They are in general much less used than the other typographic glyphs.

I was thinking of adding them under a prefix, such as `C-x 8 f i` for "ﬁ" or similar.

**Comment by tmalsburg** [comment]
I'm clearly not an expert for Unicode and didn't know about the decomposition.  However, searching for `fi` doesn't match the ﬁ ligature in any program that I tested including the default PDF viewer on my system and Firefox (v36 on Ubuntu 14.04).  As long as that is the case, I think it is better not to use ligatures even if the Unicode standard has a solution on for that.

Not sure if I agree with the comparison to quotation marks.  When searching `"`, I would not expect other quotation marks such as `“` to match but when I search for `final`, I definitely expect `ﬁnal`(with ligature) to match.  But I should shut up since you're not planning to implement ligatures anyway in the near future :)

Regarding the problem with `self` vs `welfare`, is the difference that in `welfare` the ligature would cross morphological boundaries within the word? If yes, that's indeed a difficult problem unless you have a very good dictionary available.

**Comment by jorgenschaefer** [comment]
Funny. Chromium finds both versions of final in your post :-)

> Regarding the problem with `self` vs `welfare`, is the difference that in `welfare` the ligature would cross morphological boundaries within the word?

Yes, exactly. We're also moving into debatable territory – when to use a ligature and when not to can be the topic of long discussions for typography experts, and depend a lot on the general layout, including chosen font, the letter spacing used in the text, etc. It would be fine if it was "use ligatures most of the time", then we could just provide a simple way of not doing a ligature (that's what TeX does), but I don't think "most of the time" even applies.

**Comment by tmalsburg** [comment]
Just checked, Chromium works on my system, too.

> but I don't think "most of the time" even applies.

Ah, isn't it nice that there some problem left that we don't know how to solve computationally?! ;-)
